"""
Mappe di riferimento per Country Detection:
- COUNTRY_TLD_MAP: ccTLD -> (country_name, country_code ISO 3166-1 alpha-2)
- PHONE_PREFIX_MAP: prefisso telefonico -> (country_name, country_code)
- LANGUAGE_COUNTRY_MAP: codice lingua -> (country_name, country_code)
"""

# === COUNTRY TLD MAP (200+ ccTLD) ===
COUNTRY_TLD_MAP: dict[str, tuple[str, str]] = {
    "ac": ("Ascension Island", "AC"),
    "ad": ("Andorra", "AD"),
    "ae": ("United Arab Emirates", "AE"),
    "af": ("Afghanistan", "AF"),
    "ag": ("Antigua and Barbuda", "AG"),
    "ai": ("Anguilla", "AI"),
    "al": ("Albania", "AL"),
    "am": ("Armenia", "AM"),
    "ao": ("Angola", "AO"),
    "ar": ("Argentina", "AR"),
    "as": ("American Samoa", "AS"),
    "at": ("Austria", "AT"),
    "au": ("Australia", "AU"),
    "aw": ("Aruba", "AW"),
    "ax": ("Aland Islands", "AX"),
    "az": ("Azerbaijan", "AZ"),
    "ba": ("Bosnia and Herzegovina", "BA"),
    "bb": ("Barbados", "BB"),
    "bd": ("Bangladesh", "BD"),
    "be": ("Belgium", "BE"),
    "bf": ("Burkina Faso", "BF"),
    "bg": ("Bulgaria", "BG"),
    "bh": ("Bahrain", "BH"),
    "bi": ("Burundi", "BI"),
    "bj": ("Benin", "BJ"),
    "bm": ("Bermuda", "BM"),
    "bn": ("Brunei", "BN"),
    "bo": ("Bolivia", "BO"),
    "br": ("Brazil", "BR"),
    "bs": ("Bahamas", "BS"),
    "bt": ("Bhutan", "BT"),
    "bw": ("Botswana", "BW"),
    "by": ("Belarus", "BY"),
    "bz": ("Belize", "BZ"),
    "ca": ("Canada", "CA"),
    "cc": ("Cocos Islands", "CC"),
    "cd": ("Democratic Republic of the Congo", "CD"),
    "cf": ("Central African Republic", "CF"),
    "cg": ("Republic of the Congo", "CG"),
    "ch": ("Switzerland", "CH"),
    "ci": ("Ivory Coast", "CI"),
    "ck": ("Cook Islands", "CK"),
    "cl": ("Chile", "CL"),
    "cm": ("Cameroon", "CM"),
    "cn": ("China", "CN"),
    "co": ("Colombia", "CO"),
    "cr": ("Costa Rica", "CR"),
    "cu": ("Cuba", "CU"),
    "cv": ("Cape Verde", "CV"),
    "cw": ("Curacao", "CW"),
    "cy": ("Cyprus", "CY"),
    "cz": ("Czech Republic", "CZ"),
    "de": ("Germany", "DE"),
    "dj": ("Djibouti", "DJ"),
    "dk": ("Denmark", "DK"),
    "dm": ("Dominica", "DM"),
    "do": ("Dominican Republic", "DO"),
    "dz": ("Algeria", "DZ"),
    "ec": ("Ecuador", "EC"),
    "ee": ("Estonia", "EE"),
    "eg": ("Egypt", "EG"),
    "er": ("Eritrea", "ER"),
    "es": ("Spain", "ES"),
    "et": ("Ethiopia", "ET"),
    "eu": ("European Union", "EU"),
    "fi": ("Finland", "FI"),
    "fj": ("Fiji", "FJ"),
    "fk": ("Falkland Islands", "FK"),
    "fm": ("Micronesia", "FM"),
    "fo": ("Faroe Islands", "FO"),
    "fr": ("France", "FR"),
    "ga": ("Gabon", "GA"),
    "gd": ("Grenada", "GD"),
    "ge": ("Georgia", "GE"),
    "gf": ("French Guiana", "GF"),
    "gg": ("Guernsey", "GG"),
    "gh": ("Ghana", "GH"),
    "gi": ("Gibraltar", "GI"),
    "gl": ("Greenland", "GL"),
    "gm": ("Gambia", "GM"),
    "gn": ("Guinea", "GN"),
    "gp": ("Guadeloupe", "GP"),
    "gq": ("Equatorial Guinea", "GQ"),
    "gr": ("Greece", "GR"),
    "gt": ("Guatemala", "GT"),
    "gu": ("Guam", "GU"),
    "gw": ("Guinea-Bissau", "GW"),
    "gy": ("Guyana", "GY"),
    "hk": ("Hong Kong", "HK"),
    "hn": ("Honduras", "HN"),
    "hr": ("Croatia", "HR"),
    "ht": ("Haiti", "HT"),
    "hu": ("Hungary", "HU"),
    "id": ("Indonesia", "ID"),
    "ie": ("Ireland", "IE"),
    "il": ("Israel", "IL"),
    "im": ("Isle of Man", "IM"),
    "in": ("India", "IN"),
    "io": ("British Indian Ocean Territory", "IO"),
    "iq": ("Iraq", "IQ"),
    "ir": ("Iran", "IR"),
    "is": ("Iceland", "IS"),
    "it": ("Italy", "IT"),
    "je": ("Jersey", "JE"),
    "jm": ("Jamaica", "JM"),
    "jo": ("Jordan", "JO"),
    "jp": ("Japan", "JP"),
    "ke": ("Kenya", "KE"),
    "kg": ("Kyrgyzstan", "KG"),
    "kh": ("Cambodia", "KH"),
    "ki": ("Kiribati", "KI"),
    "km": ("Comoros", "KM"),
    "kn": ("Saint Kitts and Nevis", "KN"),
    "kp": ("North Korea", "KP"),
    "kr": ("South Korea", "KR"),
    "kw": ("Kuwait", "KW"),
    "ky": ("Cayman Islands", "KY"),
    "kz": ("Kazakhstan", "KZ"),
    "la": ("Laos", "LA"),
    "lb": ("Lebanon", "LB"),
    "lc": ("Saint Lucia", "LC"),
    "li": ("Liechtenstein", "LI"),
    "lk": ("Sri Lanka", "LK"),
    "lr": ("Liberia", "LR"),
    "ls": ("Lesotho", "LS"),
    "lt": ("Lithuania", "LT"),
    "lu": ("Luxembourg", "LU"),
    "lv": ("Latvia", "LV"),
    "ly": ("Libya", "LY"),
    "ma": ("Morocco", "MA"),
    "mc": ("Monaco", "MC"),
    "md": ("Moldova", "MD"),
    "me": ("Montenegro", "ME"),
    "mg": ("Madagascar", "MG"),
    "mh": ("Marshall Islands", "MH"),
    "mk": ("North Macedonia", "MK"),
    "ml": ("Mali", "ML"),
    "mm": ("Myanmar", "MM"),
    "mn": ("Mongolia", "MN"),
    "mo": ("Macau", "MO"),
    "mp": ("Northern Mariana Islands", "MP"),
    "mq": ("Martinique", "MQ"),
    "mr": ("Mauritania", "MR"),
    "ms": ("Montserrat", "MS"),
    "mt": ("Malta", "MT"),
    "mu": ("Mauritius", "MU"),
    "mv": ("Maldives", "MV"),
    "mw": ("Malawi", "MW"),
    "mx": ("Mexico", "MX"),
    "my": ("Malaysia", "MY"),
    "mz": ("Mozambique", "MZ"),
    "na": ("Namibia", "NA"),
    "nc": ("New Caledonia", "NC"),
    "ne": ("Niger", "NE"),
    "nf": ("Norfolk Island", "NF"),
    "ng": ("Nigeria", "NG"),
    "ni": ("Nicaragua", "NI"),
    "nl": ("Netherlands", "NL"),
    "no": ("Norway", "NO"),
    "np": ("Nepal", "NP"),
    "nr": ("Nauru", "NR"),
    "nu": ("Niue", "NU"),
    "nz": ("New Zealand", "NZ"),
    "om": ("Oman", "OM"),
    "pa": ("Panama", "PA"),
    "pe": ("Peru", "PE"),
    "pf": ("French Polynesia", "PF"),
    "pg": ("Papua New Guinea", "PG"),
    "ph": ("Philippines", "PH"),
    "pk": ("Pakistan", "PK"),
    "pl": ("Poland", "PL"),
    "pm": ("Saint Pierre and Miquelon", "PM"),
    "pn": ("Pitcairn Islands", "PN"),
    "pr": ("Puerto Rico", "PR"),
    "ps": ("Palestine", "PS"),
    "pt": ("Portugal", "PT"),
    "pw": ("Palau", "PW"),
    "py": ("Paraguay", "PY"),
    "qa": ("Qatar", "QA"),
    "re": ("Reunion", "RE"),
    "ro": ("Romania", "RO"),
    "rs": ("Serbia", "RS"),
    "ru": ("Russia", "RU"),
    "rw": ("Rwanda", "RW"),
    "sa": ("Saudi Arabia", "SA"),
    "sb": ("Solomon Islands", "SB"),
    "sc": ("Seychelles", "SC"),
    "sd": ("Sudan", "SD"),
    "se": ("Sweden", "SE"),
    "sg": ("Singapore", "SG"),
    "sh": ("Saint Helena", "SH"),
    "si": ("Slovenia", "SI"),
    "sk": ("Slovakia", "SK"),
    "sl": ("Sierra Leone", "SL"),
    "sm": ("San Marino", "SM"),
    "sn": ("Senegal", "SN"),
    "so": ("Somalia", "SO"),
    "sr": ("Suriname", "SR"),
    "ss": ("South Sudan", "SS"),
    "st": ("Sao Tome and Principe", "ST"),
    "sv": ("El Salvador", "SV"),
    "sx": ("Sint Maarten", "SX"),
    "sy": ("Syria", "SY"),
    "sz": ("Eswatini", "SZ"),
    "tc": ("Turks and Caicos Islands", "TC"),
    "td": ("Chad", "TD"),
    "tg": ("Togo", "TG"),
    "th": ("Thailand", "TH"),
    "tj": ("Tajikistan", "TJ"),
    "tk": ("Tokelau", "TK"),
    "tl": ("Timor-Leste", "TL"),
    "tm": ("Turkmenistan", "TM"),
    "tn": ("Tunisia", "TN"),
    "to": ("Tonga", "TO"),
    "tr": ("Turkey", "TR"),
    "tt": ("Trinidad and Tobago", "TT"),
    "tv": ("Tuvalu", "TV"),
    "tw": ("Taiwan", "TW"),
    "tz": ("Tanzania", "TZ"),
    "ua": ("Ukraine", "UA"),
    "ug": ("Uganda", "UG"),
    "uk": ("United Kingdom", "GB"),
    "us": ("United States", "US"),
    "uy": ("Uruguay", "UY"),
    "uz": ("Uzbekistan", "UZ"),
    "va": ("Vatican City", "VA"),
    "vc": ("Saint Vincent and the Grenadines", "VC"),
    "ve": ("Venezuela", "VE"),
    "vg": ("British Virgin Islands", "VG"),
    "vi": ("US Virgin Islands", "VI"),
    "vn": ("Vietnam", "VN"),
    "vu": ("Vanuatu", "VU"),
    "wf": ("Wallis and Futuna", "WF"),
    "ws": ("Samoa", "WS"),
    "ye": ("Yemen", "YE"),
    "yt": ("Mayotte", "YT"),
    "za": ("South Africa", "ZA"),
    "zm": ("Zambia", "ZM"),
    "zw": ("Zimbabwe", "ZW"),
}

# TLD composti -> ccTLD semplice (per gestire co.uk, com.au, ecc.)
COMPOUND_TLD_MAP: dict[str, str] = {
    "co.uk": "uk",
    "org.uk": "uk",
    "me.uk": "uk",
    "ac.uk": "uk",
    "com.au": "au",
    "net.au": "au",
    "org.au": "au",
    "com.br": "br",
    "org.br": "br",
    "net.br": "br",
    "co.jp": "jp",
    "or.jp": "jp",
    "ne.jp": "jp",
    "co.kr": "kr",
    "or.kr": "kr",
    "com.cn": "cn",
    "net.cn": "cn",
    "org.cn": "cn",
    "co.in": "in",
    "net.in": "in",
    "org.in": "in",
    "com.mx": "mx",
    "org.mx": "mx",
    "com.ar": "ar",
    "com.co": "co",
    "co.za": "za",
    "org.za": "za",
    "co.nz": "nz",
    "org.nz": "nz",
    "com.tr": "tr",
    "org.tr": "tr",
    "com.sg": "sg",
    "com.my": "my",
    "co.id": "id",
    "com.ph": "ph",
    "com.eg": "eg",
    "com.ng": "ng",
    "co.ke": "ke",
    "com.pk": "pk",
    "com.sa": "sa",
    "com.ua": "ua",
    "com.pl": "pl",
}

# === PHONE PREFIX MAP ===
PHONE_PREFIX_MAP: dict[str, tuple[str, str]] = {
    "1": ("United States", "US"),
    "7": ("Russia", "RU"),
    "20": ("Egypt", "EG"),
    "27": ("South Africa", "ZA"),
    "30": ("Greece", "GR"),
    "31": ("Netherlands", "NL"),
    "32": ("Belgium", "BE"),
    "33": ("France", "FR"),
    "34": ("Spain", "ES"),
    "36": ("Hungary", "HU"),
    "39": ("Italy", "IT"),
    "40": ("Romania", "RO"),
    "41": ("Switzerland", "CH"),
    "43": ("Austria", "AT"),
    "44": ("United Kingdom", "GB"),
    "45": ("Denmark", "DK"),
    "46": ("Sweden", "SE"),
    "47": ("Norway", "NO"),
    "48": ("Poland", "PL"),
    "49": ("Germany", "DE"),
    "51": ("Peru", "PE"),
    "52": ("Mexico", "MX"),
    "53": ("Cuba", "CU"),
    "54": ("Argentina", "AR"),
    "55": ("Brazil", "BR"),
    "56": ("Chile", "CL"),
    "57": ("Colombia", "CO"),
    "58": ("Venezuela", "VE"),
    "60": ("Malaysia", "MY"),
    "61": ("Australia", "AU"),
    "62": ("Indonesia", "ID"),
    "63": ("Philippines", "PH"),
    "64": ("New Zealand", "NZ"),
    "65": ("Singapore", "SG"),
    "66": ("Thailand", "TH"),
    "81": ("Japan", "JP"),
    "82": ("South Korea", "KR"),
    "84": ("Vietnam", "VN"),
    "86": ("China", "CN"),
    "90": ("Turkey", "TR"),
    "91": ("India", "IN"),
    "92": ("Pakistan", "PK"),
    "93": ("Afghanistan", "AF"),
    "94": ("Sri Lanka", "LK"),
    "95": ("Myanmar", "MM"),
    "98": ("Iran", "IR"),
    "212": ("Morocco", "MA"),
    "213": ("Algeria", "DZ"),
    "216": ("Tunisia", "TN"),
    "218": ("Libya", "LY"),
    "220": ("Gambia", "GM"),
    "221": ("Senegal", "SN"),
    "234": ("Nigeria", "NG"),
    "249": ("Sudan", "SD"),
    "254": ("Kenya", "KE"),
    "255": ("Tanzania", "TZ"),
    "256": ("Uganda", "UG"),
    "260": ("Zambia", "ZM"),
    "261": ("Madagascar", "MG"),
    "263": ("Zimbabwe", "ZW"),
    "351": ("Portugal", "PT"),
    "352": ("Luxembourg", "LU"),
    "353": ("Ireland", "IE"),
    "354": ("Iceland", "IS"),
    "355": ("Albania", "AL"),
    "356": ("Malta", "MT"),
    "357": ("Cyprus", "CY"),
    "358": ("Finland", "FI"),
    "359": ("Bulgaria", "BG"),
    "370": ("Lithuania", "LT"),
    "371": ("Latvia", "LV"),
    "372": ("Estonia", "EE"),
    "373": ("Moldova", "MD"),
    "374": ("Armenia", "AM"),
    "375": ("Belarus", "BY"),
    "380": ("Ukraine", "UA"),
    "381": ("Serbia", "RS"),
    "385": ("Croatia", "HR"),
    "386": ("Slovenia", "SI"),
    "387": ("Bosnia and Herzegovina", "BA"),
    "389": ("North Macedonia", "MK"),
    "420": ("Czech Republic", "CZ"),
    "421": ("Slovakia", "SK"),
    "852": ("Hong Kong", "HK"),
    "853": ("Macau", "MO"),
    "855": ("Cambodia", "KH"),
    "856": ("Laos", "LA"),
    "880": ("Bangladesh", "BD"),
    "886": ("Taiwan", "TW"),
    "960": ("Maldives", "MV"),
    "961": ("Lebanon", "LB"),
    "962": ("Jordan", "JO"),
    "963": ("Syria", "SY"),
    "964": ("Iraq", "IQ"),
    "965": ("Kuwait", "KW"),
    "966": ("Saudi Arabia", "SA"),
    "967": ("Yemen", "YE"),
    "968": ("Oman", "OM"),
    "971": ("United Arab Emirates", "AE"),
    "972": ("Israel", "IL"),
    "973": ("Bahrain", "BH"),
    "974": ("Qatar", "QA"),
    "975": ("Bhutan", "BT"),
    "976": ("Mongolia", "MN"),
    "977": ("Nepal", "NP"),
    "992": ("Tajikistan", "TJ"),
    "993": ("Turkmenistan", "TM"),
    "994": ("Azerbaijan", "AZ"),
    "995": ("Georgia", "GE"),
    "996": ("Kyrgyzstan", "KG"),
    "998": ("Uzbekistan", "UZ"),
}

# === LANGUAGE COUNTRY MAP ===
LANGUAGE_COUNTRY_MAP: dict[str, tuple[str, str]] = {
    "it": ("Italy", "IT"),
    "en": ("United Kingdom", "GB"),
    "fr": ("France", "FR"),
    "de": ("Germany", "DE"),
    "es": ("Spain", "ES"),
    "pt": ("Portugal", "PT"),
    "nl": ("Netherlands", "NL"),
    "pl": ("Poland", "PL"),
    "ro": ("Romania", "RO"),
    "hu": ("Hungary", "HU"),
    "cs": ("Czech Republic", "CZ"),
    "sk": ("Slovakia", "SK"),
    "bg": ("Bulgaria", "BG"),
    "hr": ("Croatia", "HR"),
    "sl": ("Slovenia", "SI"),
    "sr": ("Serbia", "RS"),
    "bs": ("Bosnia and Herzegovina", "BA"),
    "mk": ("North Macedonia", "MK"),
    "sq": ("Albania", "AL"),
    "el": ("Greece", "GR"),
    "tr": ("Turkey", "TR"),
    "ru": ("Russia", "RU"),
    "uk": ("Ukraine", "UA"),
    "be": ("Belarus", "BY"),
    "lt": ("Lithuania", "LT"),
    "lv": ("Latvia", "LV"),
    "et": ("Estonia", "EE"),
    "fi": ("Finland", "FI"),
    "sv": ("Sweden", "SE"),
    "no": ("Norway", "NO"),
    "da": ("Denmark", "DK"),
    "is": ("Iceland", "IS"),
    "ar": ("Saudi Arabia", "SA"),
    "he": ("Israel", "IL"),
    "fa": ("Iran", "IR"),
    "hi": ("India", "IN"),
    "bn": ("Bangladesh", "BD"),
    "ta": ("India", "IN"),
    "te": ("India", "IN"),
    "ur": ("Pakistan", "PK"),
    "zh-cn": ("China", "CN"),
    "zh-tw": ("Taiwan", "TW"),
    "ja": ("Japan", "JP"),
    "ko": ("South Korea", "KR"),
    "th": ("Thailand", "TH"),
    "vi": ("Vietnam", "VN"),
    "id": ("Indonesia", "ID"),
    "ms": ("Malaysia", "MY"),
    "tl": ("Philippines", "PH"),
    "sw": ("Kenya", "KE"),
    "af": ("South Africa", "ZA"),
    "am": ("Ethiopia", "ET"),
    "so": ("Somalia", "SO"),
    "ha": ("Nigeria", "NG"),
    "yo": ("Nigeria", "NG"),
    "ig": ("Nigeria", "NG"),
    "ca": ("Spain", "ES"),
    "gl": ("Spain", "ES"),
    "eu": ("Spain", "ES"),
}
